### ISSUE TITLE
Download not robust

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#111]
Users complain that they cannot download their data (the wheel is spinning forever). The celery worker does not seem to be saturating, so I am not sure what the problem is but fixing this should be a priority: 

![image](https://github.com/stanfordnmbl/opencap-api/assets/19328993/d8432393-0e54-45f8-8f9f-afd81e9f2346)

I can privately share a session for which it is a problem.

**Comment by nickbianco** [comment]
@antoinefalisse will discuss with Keenon and @AlbertoCasasOrtiz to discuss potential fixes, might be assign to freelancers.

**Comment by antoinefalisse** [comment]
Fixed with #115, was not a problem of CPU/Memory but a problem caused by trying to download something from S3 that was not actually existing. This was happening when for instance some trials were missing videos. Added a bunch of try except, and all tests I did worked.
