### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#137]
Add option for user to delete their account and all their data.

**Comment by AlbertoCasasOrtiz** [comment]
Will this completely erase all sessions, trials, videos, results, subjects, analysis results, tokens, etc., associated with the user, without any option for recovery?

I'm considering two options:
- If the user chooses to delete, we remove the user, and I think according to current configuration, this will remove all associated data, with no possibility of data or account recovery.
- If the user opts to delete the account, we flag the user as "disabled" in the database using a boolean. If the user logs in within 30 days, the account is restored and we show a message. However, if the user does not log in during this period, the account, along with all information, is permanently deleted.

The second option allows for data and account recovery if the user has second thoughts, but the first option is easier to implement. What are your thoughts? @antoinefalisse @suhlrich

**Comment by AlbertoCasasOrtiz** [comment]
I am implementing option 1 since it will be easier.

In the GUI I'll do as in Addbiomechanics. I will show a big DANGER red message telling users this action cannot be undone, and I will ask the users to type in their username to confirm.
