### ISSUE TITLE
calibration should not be `done` if only one camera

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#139]
See here: https://api.opencap.ai/sessions/2a5f8b56-079d-4896-aeb9-dc949688836c/
I did get the error message on the frontend, but I think an error should be thrown and the status should not be done.

Thoughts @suhlrich and @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
I agree, this would make things easier and save resources

**Comment by suhlrich** [comment]
so whenever the frontend encounters a 'wrong number of cameras error' (eg 1 camera or < nCalibratedCameras) should we error the trial immediately? We could check this before the frontend sends a stop request, and have a variable in the stop request to error the trial immediately.

**Comment by AlbertoCasasOrtiz** [comment]
This was solved when n_calibrated_cameras was done. Now instead of having status "done" and uploading a video, the status is "error", and an error message is appended to meta and show to user: "No videos uploaded. Ensure phones are connected and you have stable internet connection."
