### ISSUE TITLE
Queues / calibration / neutral

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#22]
We thought about dedicating a worker to handle calibration and neutral trials. The motivation being to improve the user experience in case all workers are busy with processing trials and users end up waiting for their calibration/neutral to go through. A few thoughts to get this started:

1. I do not think it is a good idea to have a single worker handling all these trials. I would rather have a worker only picking these trials, but all the other workers also could is they are free. That way we do not rely on a single worker only (if that one crashes, then we would be screwed).
2. We could distinguish calibration and neutral. The main reason being that calibration only requires CPU, so we could have a small machine running on AWS. Neutral trials are very short and recorded at 30Hz (I think we could even go lower), so we could have another small worker (that one with a GPU).

Let's brainstorm on that @suhlrich and @AlbertoCasasOrtiz. Not a super high priority.

**Comment by suhlrich** [comment]
Good idea. An implementation idea:
1) add a cmd line argument to app.py that distinguishes the worker to be 'calibration' or 'all' (all would be default). Could then change this in the dockerfile when we deploy. 
2) in app.py, we add an argument to the dequeue request ('all' vs 'calibration')
