### ISSUE TITLE
advanced analyses

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#43]
We would like to start working on advanced analyses that would be available for users on the frontend. An example analysis would be to automatically extract gait parameters and display them on a dashboard. Once we have the pipeline established, we can start adding analyses. Advanced analyses would be useful for practitioners with little programming experience. How I see it implemented is an additional option in the menu of the trials. The option would be _analyze_ and then the different analyses would available (eg, _gait analysis_).

Each analysis would basically be a python script (likely using OpenSim and some other libraries like numpy and pandas) that would take a motion file as input (csv) and would spit out a dictionnary or something like that. No heavy compute should be involved.

It seems straightforward to implement that through the API, but it might not be ideal as it might bug it down. Maybe AWS Lambda functions are better suited?

Thoughts @suhlrich and @AlbertoCasasOrtiz ?

**Comment by suhlrich** [comment]
We def. don't want to do it on the API machines. We're hopefully making data collection more robust by taking tasks from those machines, so let's keep them just responding to simple requests about the database.

Lambda is a good idea. You can set up a lambda with AWS gateway API, such that it just responds to http requests. The flow could be as follows:

1) front end, selects an analysis, sends http request directly to gateway API, which fires the lambda function (http request parameters are passed into lambda function)
2) figure out how to use opencap processing in lambda
     - github action -> docker image to S3.
     - github action to zip repo and dependencies,-> push to s3, run on python lambda instance
3) the lambda function responds to the gateway api request with the data

We'll want help automating this all into teraform too.

**Comment by suhlrich** [comment]
After Oleh and I discussed:

Frontend:
-menu for a trial to do an analysis
- in plotter - ability to plot from analyses
     - show in plotter that an analysis is queued if there is an empty result instance with tag=='analysis-<analysisType>'

API:
- create a result instance without data
- mapping between available analyses and lambda endpoints

Lamba:
- respond to endpoint, analyze, upload to S3 into already-made result instance

TODO:
Stanford create some analyses and test manually with lambda. Will the zipped environment be huge with opensim?

**Comment by antoinefalisse** [comment]
@suhlrich @olehkorkh-planeks @anastasiiadidan why don't we get started with this one.

**I created an [example ](https://github.com/antoinefalisse/opencap-lambda/blob/main/example.py)analysis [in this repository](https://github.com/antoinefalisse/opencap-lambda):**
- The analysis takes as input a [session_ID](https://github.com/antoinefalisse/opencap-lambda/blob/main/example.py#L28) and a [trial_name](https://github.com/antoinefalisse/opencap-lambda/blob/main/example.py#L31), does [some computation](https://github.com/antoinefalisse/opencap-lambda/blob/main/example.py#L39), and returns a [dictionary](https://github.com/antoinefalisse/opencap-lambda/blob/main/example.py#L46).
- I wrapped up everything in a [docker container](https://github.com/antoinefalisse/opencap-lambda/blob/main/Dockerfile), take a look at the [readme ](https://github.com/antoinefalisse/opencap-lambda/blob/main/README.md) for commands to run the container locally


**The idea would be to:**
- trigger the analysis from the frontend by adding an option `test_analysis` in the drop-down menu of the trial
    - The analysis would be run in a lambda function 
- save the resulting dictionary under `results` in the database with tag `test_analysis`
- plot some data on the frontend => let's make this a separate issue

@olehkorkh-planeks and @anastasiiadidan Could you let me know what else you would need to get started?
@suhlrich anything you want to add?

Ps: when the pipeline is established, we can create a clean repo with all the analyses, or whatever makes most sense.

**Comment by antoinefalisse** [comment]
The pipeline is working, I have hidden the analysis button on the viewer side because we do not have a compelling use case yet.
