### ISSUE TITLE
Multiple videos, same phone with bad network

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#46]
Sometimes with sketchy wifi, a phone creates 2 video instances. Then the trial never shows up as uploaded.

1) investigate how this could happen (slow network -> phone communicating with two servers at same time?)
2) if can't solve 1, have some check when we press stop to delete redundant instances

**Comment by antoinefalisse** [comment]
Having a spotty wifi here and it just happened: https://dev.opencap.ai/sessions/9d8eaedb-bc71-4ac9-81fb-b6696c3e59b6. I should be able to reproduce, thoughts about debugging process?

**Comment by suhlrich** [comment]
The first time the camera calls `/get_status` for a trial, a video model is created (https://github.com/stanfordnmbl/opencap-api/blob/39f3094d519aaa710f727beb8759f290ad0d9e38/mcserver/views.py#L418). My guess is with bad wifi, there's some delay in the requests such that the first and second request from a phone come super close together. One gets picked up by one API machine, the second gets picked up by the second machine. Both create a video model.

One solution would be to check for redundant video models when when the webapp stops the video, before it changes the state in the database. here https://github.com/stanfordnmbl/opencap-api/blob/39f3094d519aaa710f727beb8759f290ad0d9e38/mcserver/views.py#LL690C1-L690C1

If you like this sol'n @antoinefalisse , let's make a nice issue for Planeks

**Comment by suhlrich** [comment]
confirmed. this happens when internet has high latency (e.g., the hotspot). Will implement fix.
