### ISSUE TITLE
A new session is created every time you land on step1 page

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#5]
See details here: https://github.com/stanfordnmbl/opencap-api-private/issues/97

**Comment by AlbertoCasasOrtiz** [comment]
Last Tuesday we discussed that it could be good if we solve this at session creation time.

When we create a session, we check if the last session was used.
- If it was used, we don't touch it and create a new session.
- if it was not used (e.g., there are no trials, not even calibration trial), we have two options:
  - Reuse it.
  - Remove it and create a new session (possibly simpler with the current implementation).

**Comment by suhlrich** [comment]
solved by https://github.com/stanfordnmbl/opencap-api/issues/82
