### ISSUE TITLE
delete sessions from a user on celery

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#75]
We'd like to add an endpoint that searches for and delete all sessions from the user 'pingdom'. Once we've done this, let's call this endpoint with the celery machine once every hour.

FYI @antoinefalisse

**Comment by anastasiiadidan** [comment]
@suhlrich Do you want this feature work from the Celery only? Do you need this as actual endpoint as well?

**Comment by suhlrich** [comment]
I guess we do not need an endpoint, just work from celery.

On Jun 1, 2023, at 9:52 PM, Anastasiia Didan ***@***.***> wrote:

﻿

@suhlrich<https://github.com/suhlrich> Do you want this feature work from the Celery only? Do you need this as actual endpoint as well?

**Comment by antoinefalisse** [comment]
Closed with #78
