### ISSUE TITLE
display subject number in list in admin console

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#76]
If we want to change what subject is associated with a session thru the admin console, we need to know the subject number. This number is very hard to find. Can we add subject number in the subjects table?

**Comment by anastasiiadidan** [comment]
@suhlrich sure

**Comment by anastasiiadidan** [comment]
@suhlrich please, merge this PR https://github.com/stanfordnmbl/opencap-api/pull/77
