### ISSUE TITLE
cannot download data from public session if not your session

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#79]
If you are not logged in, you cannot download data from a session, even if public. Not sure what we want there, do we want to allow or not? We should either remove the button (if we do not allow) or make possible (if we keep the button). Thoughts @suhlrich ?

**Comment by suhlrich** [comment]
I think we do want to be able to download data from public sessions if not logged in.

On Jun 3, 2023, at 5:25 AM, Antoine Falisse ***@***.***> wrote:

﻿

If you are not logged in, you cannot download data from a session, even if public. Not sure what we want there, do we want to allow or not? Thoughts @suhlrich<https://github.com/suhlrich> ?

**Comment by antoinefalisse** [comment]
@anastasiiadidan could we make possible downloading public sessions by anyone? Currently, you need to be logged in. Here is an example: https://dev.app.opencap.ai/session/00e58b94-c70c-4835-81a0-e45abc3efcfc

**Comment by anastasiiadidan** [comment]
@antoinefalisse sure, will work on it
