### ISSUE TITLE
download fails on large sessions

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#87]
From forum. Download fails for large sessions, eg https://app.opencap.ai/session/4a2994fc-5ed2-454e-872c-d662bdc7a581. I expect the celery worker ran out of storage? @antoinefalisse thoughts?

**Comment by antoinefalisse** [comment]
I will try out and upgrade the workers accordingly.

**Comment by antoinefalisse** [comment]
@suhlrich and @AlbertoCasasOrtiz, this session has over 100 trials with 4 videos each. Do we really want to upgrade our celery workers to handle this? I could see two alternative options:
1. Give option to NOT download videos, maybe this makes things faster. We could add a box that they could tick to download videos, and by default we would not download videos. Or the other way around.
2. Have an error message after ~5min saying that they should use opencap-processing instead.

**Comment by suhlrich** [comment]
We need to cap the resources somewhere, and a session can be infinitely large. I recommend if they have > ##(30?) trials, we don't allow download and point them to the colab.

**Comment by suhlrich** [comment]
bump the celery machines?

**Comment by antoinefalisse** [comment]
Took a while (10-15) but even that one worked. I think it is fine, the folder is >7Gb.
