### ISSUE TITLE
Download sessions zip saved indefinitely on API server

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#9]
We never delete the zipped folder https://github.com/stanfordnmbl/opencap-api/blob/aeff88cc190fe137d151648cb27546755de31954/mcserver/views.py#L396 after responding to the download request. Therefore the zipped folders build up on the API server and it eventually runs out of disk space.

Since that function sends the 'session_zip' (a path name) as the response, I don't see how to delete it within that function. I guess we could have a deleteZip endpoint that the viewer would call once the download is finished? Other more clever ideas @antoinefalisse @AlbertoCasasOrtiz

**Comment by antoinefalisse** [comment]
Seems like it could be deleted in a similar way as what Plannek is implementing (see videos of the day) with celery and celery beat, ie add a time to when it was created, and trash after some time.

**Comment by suhlrich** [comment]
Agreed. I think that makes sense. So the celery worker would do something like:

`from zipsession import getDataDirectory
import os

dataDir = getDataDirectory(isDocker=True)
cleanDir = os.path.join(dataDir,'Data')

# find and delete all folders in cleanDir created more than 1 day ago
`

**Comment by antoinefalisse** [comment]
yeps

**Comment by suhlrich** [comment]
leave it for another round of Plannek?

**Comment by antoinefalisse** [comment]
yes, that works.

**Comment by suhlrich** [comment]
An easy solution here:
Whenever we run the downloadAndZip function, we look for any zipped folders that are more than 15 mins old, and delete them. This way we don't have to add a timed garbage collector.

I will implement soon.

**Comment by antoinefalisse** [comment]
Done
