### ISSUE TITLE
cannot download public session from another user when logged in

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#92]
If I am logged in and try to download a public session that is not mine, `/sessions/<session_id>/async-download/` returns 404. I should be able to download this session when logged in. 

Example session: https://app.opencap.ai/session/7272a71a-e70a-4794-a253-39e11cb7542c

**Comment by olehkorkh-planeks** [comment]
The fix https://github.com/stanfordnmbl/opencap-api/pull/128
